server.port: 9010

spring:
    profiles.active: dev
#    main.web-application-type: none

---

spring:
    profiles: dev
    datasource:
        url: jdbc:h2:mem:rdb_sample
        username: dev
        password: 1234
    h2.console.enabled: true

---

spring:
    profiles: demo, test
    jpa:
        # This `ddl-auto` property has different defaults depending on the database we use.
        # If we use an embedded database (H2, HSQL, or Derby),
        # it defaults to `create-drop`; otherwise, it defaults to `none`.
        hibernate.ddl-auto: update
    datasource:
        url: jdbc:postgresql://john.db.elephantsql.com:5432/sumtsrsf
        username: sumtsrsf
        password: zjDVe1suj-n3rzVwxuQywvKrxsVStP_m

---

spring:
    profiles: demo
    jpa.show-sql: false

---

spring:
    profiles: test, dev
    jpa:
        # Set these 2 properties to `true` when we need to see the SQL.
        show-sql: true
        properties.hibernate.format_sql: true